In [2]:
import numpy as np
# depth_path = '/home/link/Projects/curly_slam/data/tartanair/scenes/abandonedfactory/Easy/P001/depth_left/000000_left_depth.npy'
# depth = np.load(depth_path)
# depth[389,594]

In [6]:
a = np.arange(3).reshape([3,1])
a[1]

array([1])

In [7]:
from spatialmath import SE3


In [10]:
a=SE3()
a.R,a.t

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([0., 0., 0.]))